drop table subscriber if exists;

create table subscriber (
    id integer generated by default as identity primary key,
    name varchar(80) not null,
    email varchar(256) not null
);

drop table subscriber_topic if exists;

create table subscriber_topic (
    id integer generated by default as identity primary key,
    subscriber_id integer not null,
    topic_id integer not null
);

drop table topic if exists;

create table topic (
    id integer generated by default as identity primary key,
    name varchar(80) not null
);

